---
title: Similar-Day Naive Method
author: Tim Radtke
date: '2025-12-01'
slug: similar-day-naive-method
categories: []
tags: []
---

Like the [Chronos-2 technical report](https://arxiv.org/abs/2510.15821), Uniejewski and Weron compare the approaches implemented in their [aforementioned](https://minimizeregret.com/note/2025/11/30/chronos-2-scaling-inverse-hyperbolic-sine) [paper](https://www.mdpi.com/1996-1073/11/8/2039) against a naive baseline. Unlike the technical report which uses seasonal naive for all data sets, Uniejewski and Weron, to their credit, employ a baseline that, while naive, is tuned to their use case of electricity price forecasting and employs as much knowledge as possible:

> The first benchmark, the so-called naive method, belongs to the class of similar-day techniques. It is defined by $\hat{P}_{d,h} = \hat{P}_{d-7,h}$ for Monday, Saturday and Sunday, and $\hat{P}_{d,h} = \hat{P}_{d-1,h}$ otherwise.
As Contreras et al. argued, forecasting procedures that are not calibrated carefully fail to outperform this extremely simple method surprisingly often.

So given the different human patterns in electricity usage on workdays and on weekends, they use the naive method for workdays and seasonal naive for the weekend and Monday (because Sunday can't be used to predict Monday).

Reminds me of [this footnote](https://minimizeregret.com/post/2022/08/30/where-is-the-seasonal-naive-benchmark/#fn1).
