---
title: Scaling Time Series Using the Inverse Hyperbolic Sine
author: Tim Radtke
date: '2025-11-30'
slug: chronos-2-scaling-inverse-hyperbolic-sine
categories: []
tags: []
---

This one's new to me: The Chronos-2 tokenization pipeline follows up an initial standardization of input time series with a variance stabilizing transformation in the *inverse hyperbolic sine function*, $\sinh^{-1}$, as described in the [model's technical report](https://arxiv.org/abs/2510.15821).

The [inverse hyperbolic sine function](https://en.wikipedia.org/wiki/Inverse_hyperbolic_functions) is defined as:

$$
\sinh^{-1}(x) = \ln(x + \sqrt{x^2+1}).
$$

As such it is an alternative to the $\ln(x+1)$ transform with the added benefit of being applicable to negative values.

While news to me, the technical report points out that the inverse hyperbolic sine is no news to the electricity price forecasting literature, citing "[Efficient Forecasting of Electricity Spot Prices with
Expert and LASSO Models](https://www.mdpi.com/1996-1073/11/8/2039)" by Bartosz Uniejewski and Rafał Weron, which describes the inverse hyperbolic sine and other variance stabilizing transformations in more detail.